Fix duplicate key ArgumentException in the Interpreter
I was seeing the following exception

```
System.ArgumentException: An item with the same key has already been added. Key: (UEntity {Name = "CounterApp.App+Model";
         GenericParameters = [||];
         UnionCases = [||];}, CompareTo, UTypes [|UNamedType ({Name = "CounterApp.App+Model";
                      GenericParameters = [||];
                      UnionCases = [||];},[||])|])
```